### ISSUE TITLE
nbdemetra 2.2.0 can not save model

### ISSUE THREAD

**Issue by marjaluo** [nbbrd/jdemetra-nowcasting#4]
AS I 2.2.0 saved a workspace as a file ,when I opened it late , the DFM model was missed .

**Comment by marjaluo** [comment]
This problem happened when I created a new model.

**Comment by Liedo** [comment]
Which version of JDemetra + are you using?  Current version of the plugn (master branch) needs the version 2.2.0 of JDemetra+ and JDK 8

**Comment by marjaluo** [comment]
I use the JDemetra+ 2.2.0 +JDK 8.
When I opened a model which I have created with 2.1.0，and changed data , saved it ,there is no problem.
But  I created a new model in JDemetra+ 2.2.0 with nbdemetra 2.2.0 , and saved  it 。When I opened the saved file again, I can not find the modle.
Thank you.

**Comment by maggima** [comment]
Hello,
We've identified the problem and we are currently working on a fix.
The workspace is not correctly being saved for Dfm documents. If you open the .xml file for your workspace, you'll notice that the documents are not referenced despite the fact that the files are present under the folder **<workspace_folder>\DfmDoc**

One quick solution before our fix is to manually edit that workspace file and add the needed reference :
``` xml
<ns2:items>
        <ns2:item readOnly="false">
            <ns2:family>Nowcasting@documents@DynamicFactorModel</ns2:family>
            <ns2:name>Model A64 (21)</ns2:name>
            <ns2:file>DfmDoc-13</ns2:file>
        </ns2:item>

        ..... Other items in the workspace ....

</ns2:items>
```
Here Model A64(21) is the name of the document in JDemetra+ (display name) and file is the name of the correponding xml file under **<workspace_folder>\DfmDoc**

Hope this helps before we release our correction.

Mats

**Comment by marjaluo** [comment]
Thank you very much.I will try,

**Comment by Liedo** [comment]
This issue is already  solved in the latest version of the Nowcasting plugin, so I'm closing it https://github.com/nbbrd/jdemetra-nowcasting/releases/tag/v2.2.1
