### ISSUE TITLE
drag and drop excel sheet

### ISSUE THREAD

**Issue by Liedo** [nbbrd/jdemetra-nowcasting#5]
There is a small problem with the drag and drop command when you use the Providers tab as a try to load your data. For some reason you have to do the gesture two times instead of one time. I made a small GIF video to illustrate the problem:

![issuedragdrop](https://user-images.githubusercontent.com/13660698/31824114-646a94a4-b5ae-11e7-8d02-b275e6cdf22b.gif)

**Comment by maggima** [comment]
Commit 09006666a57c08cb5a8d38018d107884df8876a7 should fix the issue.

**Comment by Liedo** [comment]
Thank you. I just replaced my previous plugin by the file nbdemetra-dfm-2.2.1.nbm that one can download in https://github.com/nbbrd/jdemetra-nowcasting/releases/tag/v2.2.1 and the problem is solved
